Allow to configure the number of persons to book for
reaper47/ind-appointment-checker pull request #2
Opened 2022-08-27 22:56 UTC by bardo

_Premise: I suck at Go, so please check my changes carefully. :)_

This change introduces a new configuration variable, `TOTAL_PERSONS`, which sets the number of people who need to book an appointment together. Right now the IND allows a maximum of 6 people, with each person's appointment duration set to 10 minutes. Multiple people booking together need consecutive slots to be available.

Configuring the number of persons makes the bot much less noisy for groups of people booking together because most of the slots that free up are long enough for a single person.

2022-08-29 10:05 UTC, reaper47 requested changes
Excellent work, thank you! Please check the two small comments :D

Also, we could probably add a .swp filter in the .gitignore to ignore swap files such as `internal/pkg/appointments/.appointments_test.go.swp`.

2022-08-29 10:05 UTC, reaper47 commented on internal/pkg/models/url.go
> +		Endpoint:   "/" + city.Abbrev() + "/slots/?productKey=" + productKey + "&persons=" + fmt.Sprint(persons),
We should write `fmt.Sprintf("/%s/slots/?productKey=%s&persons=%d", city.Abbrev(), productKey, persons)` because we are building a string out of multiple variables.

2022-08-29 10:05 UTC, reaper47 commented on internal/pkg/jobs/jobs.go
> +				"%s:\nAn earlier %s appointment for %s person(s) is available on %s at %s.\nBook an appointment now: https://oap.ind.nl/oap/en/#/%s",
We could write `for %d persons` instead to shorten line 86 from `fmt.Sprint(persons)` to `persons`.

2022-08-29 20:17 UTC, bardo commented
Thanks for the comments! I incorporated all the changes.

2022-08-30 06:48 UTC, reaper47 approved these changes

2022-08-30 06:48 UTC, merged